### ISSUE TITLE
whats the name of the used fonts to Change Font Size in custom.css

### ISSUE THREAD

**Issue by gallipower** [javiergayala/MMM-mqtt#8]
Hello Javier!

Is there any way to change the font size and the color from the mqtt output on my mm?
I have a mirror with dark  spyglass so i would prefer brighter and larger fonts!

thanks!

**Comment by acejacek** [comment]
You can do it with modification of `MMM-mqtt.css` file:
```
.MMM-mqtt .title , .MMM-mqtt .loading {
  font-size: 60%;
}

.MMM-mqtt .value {
  font-size: 150%;
}
```

**Comment by gallipower** [comment]
Thanks caejacek !

But for newbie: where ist the MMM-mqtt.css file located??
My commandline skills are not so good to find the file with some commands!  ;-)
I try many subfolders but cant find the file?
Do i have to create one? And when, in witch folder?
Thanks for your help and sorry for my english!

**Comment by gallipower** [comment]
And  one more question!
The status line means that i should update MMM-mqtt. 
But when i try to git clone i can´t because the folder already exist.
Should i have to delete the complete MMM-mqtt folder or ist there another way to update MMM-mqtt?
Thanks for your help!

**Comment by gallipower** [comment]
Solved!

Delete the complete MMM-mqtt folder and reinstall makes my day!
Works like a charm!
 MANY THANKS!!
